# Generated by Django 4.2.17 on 2024-12-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accident_index", models.CharField(max_length=20, unique=True)),
                ("location_easting", models.FloatField(blank=True, null=True)),
                # ("location_northing", models.FloatField(blank=True, null=True)),
                ("location_northing", models.CharField(max_length=20)),
                # ("longitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.CharField(max_length=20)),
                # ("latitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.CharField(max_length=20)),
                # ("accident_severity", models.IntegerField()),
                ("accident_severity", models.CharField(max_length=5)),
                # ("number_of_vehicles", models.IntegerField()),
                ("number_of_vehicles", models.CharField(max_length=5)),
                # ("number_of_casualties", models.IntegerField()),
                ("number_of_casualties", models.CharField(max_length=5)),
                # ("date", models.DateField()),
                ("date", models.CharField(max_length=5)),
            ],
        ),
    ]
